- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Aslam-play
  # vars_files:
  # - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter your name
    private: false
  tasks:
  - name: variable at task level
    # vars:
    #   #  NAME: Aslam-task
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"

# 1. command line variables
# 2. task level
# 3. vars_files
# 4. prompt
# 5. play
# 6. inventory
# 7. Roles
