      
- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  #play level
  vars : 
    COURSE: DevOps
    LEARNIG_MODULE: Ansible
    DURATION: 3months 
  tasks : 
  - name : inherit vars from play level
    ansible.builtin.debug:
      msg: "course : {{COURSE}} , learning_module : {{LEARNIG_MODULE}} , duration : {{DURATION}}"
  - name : inherit vars from play level
  vars : 
     TASKS: Roboshop 
     TYPE : Practice
  ansible.builtin.debug:
      msg: "course : {{COURSE}} , tasks : {{TASKS}} , type : {{Practice}}"
      
