- name: variables at task level
  hosts: localhost
  vars: 
    COURSE : DevOps
    DURATION : 3months 
  tasks:   
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "course : {{COURSE}}, duration : {{DURATION}}"
  - name: inherit values from play and add and override
    vars:
      MONEY: "20K"
    ansible.builtin.debug:
      msf: "money : {{MONEY}}"
     