- name : variable from prompt
  hosts : localhosts 
  vars_prompt:
  - name : USERNAME
    prompt : Please enter your name 
    private : false # this can enables visibily in the screen 

  - name : PASSWORD
    prompt : Please enter your password
    private : false

  tasks :
  - name : print the variable values using prompt 
    ansible.builtin.debug:
      msg : "username {{USERNAME}} , password {{PASSWORD}}"  
